apiVersion: batch/v1
kind: Job
metadata:
  name: exoplanets-job
spec:
  template:
    metadata:
      name: exoplanets-job
    spec:
      containers:
        - name: exoplanets
          image: rpairo/exoplanet-terminal:latest
          command: ["./ExoplanetTerminal"]
          env:
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: exoplanets-local-secrets
                  key: BASE_URL
            - name: PATH_SEGMENT
              valueFrom:
                secretKeyRef:
                  name: exoplanets-local-secrets
                  key: PATH_SEGMENT
            - name: ENDPOINT_EXOPLANETS
              valueFrom:
                secretKeyRef:
                  name: exoplanets-local-secrets
                  key: ENDPOINT_EXOPLANETS
      restartPolicy: Never
  backoffLimit: 0
