apiVersion: batch/v1
kind: Job
metadata:
  name: exoplanets-job
spec:
  template:
    spec:
      containers:
      - name: exoplanets
        image: rpairo/exoplanets-terminal:latest
        command: ["./ExoplanetTerminal"]
      restartPolicy: Never
  backoffLimit: 0
