apiVersion: apps/v1
kind: Deployment
metadata:
  name: exoplanets-deployment
  labels:
    app: exoplanets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exoplanets
  template:
    metadata:
      labels:
        app: exoplanets
    spec:
      containers:
      - name: exoplanets-container
        image: rpairo/exoplanets:latest
        env:
        - name: APP_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        command: ["./ExoplanetAnalyzer"]
