apiVersion: batch/v1
kind: Job
metadata:
  name: exoplanets-job
  labels:
    app: exoplanets
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      name: exoplanets-job
      labels:
        app: exoplanets
    spec:
      restartPolicy: Never
      containers:
        - name: exoplanets
          image: rpairo/exoplanets-terminal:latest
          imagePullPolicy: IfNotPresent
          command: ["./ExoplanetsTerminal"]
          env:
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: exoplanets-local-secrets
                  key: BASE_URL
            - name: PATH_SEGMENT
              valueFrom:
                secretKeyRef:
                  name: exoplanets-local-secrets
                  key: PATH_SEGMENT
            - name: ENDPOINT_EXOPLANETS
              valueFrom:
                secretKeyRef:
                  name: exoplanets-local-secrets
                  key: ENDPOINT_EXOPLANETS
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
