name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write   # Needed for Docker push or GH Packages

concurrency:
  group: build-and-deploy
  cancel-in-progress: true

jobs:
  # 1) Test Code with the reusable workflow
  test-code:
    uses: ./.github/workflows/test-swift.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  fetch-docker-creds:
    uses: ./.github/workflows/fetch-docker-credentials.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  build-scan-and-push:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - test-code
      - fetch-docker-creds

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # **Paso Nuevo: Configurar Buildx con docker-container**
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ needs.fetch-docker-creds.outputs.docker_username }}
          password: ${{ needs.fetch-docker-creds.outputs.docker_password }}

      - name: Build Docker Image (no push)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: rpairo/exoplanet-terminal:latest
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan Docker Image for ExoplanetTerminal
        uses: docker/scout-action@v1
        with:
          command: cves
          image: rpairo/exoplanet-terminal:latest
          only-severities: critical,high
          exit-code: true

      - name: Push Docker Image
        if: success()
        run: docker push rpairo/exoplanet-terminal:latest