name: CI/CD Workflow

on:
  # Ejecutar los tests para todos los Pull Requests
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  # Construir y publicar imagen solo cuando se haga un merge en main
  push:
    branches:
      - main

jobs:
  # Job 1: Validar todos los Pull Requests
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Usar la imagen Docker de Swift 6.0.3 para ejecutar los tests
      - name: Run Tests with Swift 6.0.3
        uses: docker://swift:6.0.3
        with:
          args: swift test

  # Job 2: Construir y Publicar Imagen en Docker Hub
  build-and-push:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: validate-pr

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build the Docker image
      - name: Build Docker Image
        run: docker build -t rpairo/exoplanets:latest .

      # 4. Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push rpairo/exoplanets:latest
