name: CI/CD Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

jobs:
  validate-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      
      - name: Retrieve API test configuration
        id: api-config
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-id: exoplanets-analyzer-api-url-test
          json-fields: '["BASE_URL", "PATH_SEGMENT", "ENDPOINT_EXOPLANETS"]'

      - name: Run Tests with Swift 6.0.3
        uses: docker://swift:6.0.3
        env:
          BASE_API_URL: ${{ steps.api-config.outputs.BASE_URL }}
          PATH_SEGMENT: ${{ steps.api-config.outputs.PATH_SEGMENT }}
          ENDPOINT_EXOPLANETS: ${{ steps.api-config.outputs.ENDPOINT_EXOPLANETS }}
        with:
          args: swift test

  build-and-push:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: validate-pr

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Retrieve Docker credentials
        id: docker-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-id: docker-credentials
          json-fields: '["USERNAME", "PASSWORD"]'
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ steps.docker-secrets.outputs.USERNAME }}
          password: ${{ steps.docker-secrets.outputs.PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rpairo/exoplanets:latest