name: Fetch Docker Credentials

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  fetch-docker-creds-job:
    runs-on: ubuntu-latest

    outputs:
      docker_username: ${{ steps.fetch-docker.outputs.docker_username }}
      docker_password: ${{ steps.fetch-docker.outputs.docker_password }}

    steps:
      - name: Retrieve Docker credentials
        id: fetch-docker
        run: |
          docker_secrets=$(aws secretsmanager get-secret-value \
            --secret-id docker-credentials \
            --query SecretString \
            --output text)

          DOCKER_USER=$(echo "$docker_secrets" | jq -r '.USERNAME')
          DOCKER_PASS=$(echo "$docker_secrets" | jq -r '.PASSWORD')

          echo "::add-mask::$DOCKER_USER"
          echo "::add-mask::$DOCKER_PASS"

          echo "::set-output name=docker_username::$DOCKER_USER"
          echo "::set-output name=docker_password::$DOCKER_PASS"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}