name: Reusable Swift Test

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        required: true
      path_segment:
        type: string
        required: true
      endpoint_exoplanets:
        type: string
        required: true
    secrets:
      # If you need AWS inside this test, define secrets here. Otherwise omit.
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_REGION:
        required: false

jobs:
  swift-test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint code (install + run SwiftLint)
        uses: docker://swift:6.0.3
        with:
          args: |
            bash -c "apt-get update &&
                     apt-get install -y swiftlint &&
                     swiftlint"

      - name: Run Swift Tests
        uses: docker://swift:6.0.3
        env:
          BASE_API_URL: ${{ inputs.base_url }}
          PATH_SEGMENT: ${{ inputs.path_segment }}
          ENDPOINT_EXOPLANETS: ${{ inputs.endpoint_exoplanets }}
        with:
          args: swift test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: .build