name: Reusable Swift Test

on:
  workflow_call:
    inputs:
      base_url:
        type: string
        required: true
      path_segment:
        type: string
        required: true
      endpoint_exoplanets:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      AWS_REGION:
        required: false

jobs:
  swift-test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Swift Tests
        uses: docker://swift:6.0.3
        env:
          BASE_URL: ${{ env.BASE_URL }}
          PATH_SEGMENT: ${{ env.PATH_SEGMENT }}
          ENDPOINT_EXOPLANETS: ${{ env.ENDPOINT_EXOPLANETS }}
        with:
          args: swift test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: .build