name: Pull Request Validation

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

concurrency:
  group: validate-pr
  cancel-in-progress: true

jobs:
  # 1) Fetch Exoplanet URLs
  fetch-urls:
    uses: ./.github/workflows/fetch-exoplanets-urls.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  # 2) Validate the PR (lint + test)
  validate-pr:
    if: ${{ github.event.pull_request.draft == false }}
    needs: fetch-urls
    uses: ./.github/workflows/test-swift.yml
    with:
      base_url: ${{ needs.fetch-urls.outputs.base_url }}
      path_segment: ${{ needs.fetch-urls.outputs.path_segment }}
      endpoint_exoplanets: ${{ needs.fetch-urls.outputs.endpoint_exoplanets }}