name: Pull Request Validation

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

concurrency:
  group: validate-pr
  cancel-in-progress: true

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest

    # Skip this job if the PR is a draft
    if: ${{ github.event.pull_request.draft == false }}

    steps:
      - name: Run Reusable Swift Tests
        uses: ./.github/workflows/test-swift.yml@main
        # Provide the AWS secrets needed by the reusable workflow
        secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}